---
title: "DM & ML Course Work Notebook"
output: html_notebook
---


## Objective 01

```{r}
# install the packages
install.packages("ggstatsplot")
install.packages("readxl")
install.packages("factoextra")
install.packages("NbClust")
install.packages('swamp')
```

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("impute")
```


```{r}
# Load the package
library(ggstatsplot)
library(readxl)
library(factoextra)
library(NbClust)
library(tidyverse)
library(swamp)
```

```{r}
# import Excel file into R
wineDataset <- read_excel("S:\\UoW\\YR3\\ML\\cw\\Whitewine_v2.xlsx")
```
```{r}
# get column name
names(wineDataset) <- gsub(" ", "_", names(wineDataset))
colnames(wineDataset)
```
```{r}
#demo dataset
wineDataset
```
```{r}
# Create a boxplot of the dataset, outliers are shown as two distinct points
boxplot(wineDataset)$out
```
```{r}
# find outliers and store them
outliers1 <- boxplot(wineDataset$fixed_acidity, plot = FALSE)$out
outliers2 <- boxplot(wineDataset$volatile_acidity, plot = FALSE)$out
outliers3 <- boxplot(wineDataset$citric_acid, plot = FALSE)$out
outliers4 <- boxplot(wineDataset$residual_sugar, plot = FALSE)$out
outliers5 <- boxplot(wineDataset$chlorides, plot = FALSE)$out
outliers6 <- boxplot(wineDataset$free_sulfur_dioxide, plot = FALSE)$out
outliers7 <- boxplot(wineDataset$total_sulfur_dioxide, plot = FALSE)$out
outliers8 <- boxplot(wineDataset$density, plot = FALSE)$out
outliers9 <- boxplot(wineDataset$pH, plot = FALSE)$out
outliers10 <- boxplot(wineDataset$sulphates, plot = FALSE)$out
outliers11 <- boxplot(wineDataset$alcohol, plot = FALSE)$out
```
```{r}
# restore dataset for new varibale
nill_outliers_winedataset <- wineDataset

```
```{r}
while (length(outliers4) > 0 || length(outliers6) > 0 || length(outliers7) > 0 || length(outliers9) > 0) {

    # remove outliers from new duplicated dataset
    if (length(outliers1) > 0) {
        nill_outliers_winedataset <- nill_outliers_winedataset[-which(nill_outliers_winedataset$fixed_acidity %in% outliers1), ]
    }
    if (length(outliers2) > 0) {
        nill_outliers_winedataset <- nill_outliers_winedataset[-which(nill_outliers_winedataset$volatile_acidity %in% outliers2), ]
    }
    if (length(outliers3) > 0) {
        nill_outliers_winedataset <- nill_outliers_winedataset[-which(nill_outliers_winedataset$citric_acid %in% outliers3), ]
    }
    if (length(outliers4) > 0) {
        nill_outliers_winedataset <- nill_outliers_winedataset[-which(nill_outliers_winedataset$residual_sugar %in% outliers4), ]
    }
    if (length(outliers5) > 0) {
        nill_outliers_winedataset <- nill_outliers_winedataset[-which(nill_outliers_winedataset$chlorides %in% outliers5), ]
    }
    if (length(outliers6) > 0) {
        nill_outliers_winedataset <- nill_outliers_winedataset[-which(nill_outliers_winedataset$free_sulfur_dioxide %in% outliers6), ]
    }
    if (length(outliers7) > 0) {
        nill_outliers_winedataset <- nill_outliers_winedataset[-which(nill_outliers_winedataset$total_sulfur_dioxide %in% outliers7), ]
    }
    if (length(outliers9) > 0) {
        nill_outliers_winedataset <- nill_outliers_winedataset[-which(nill_outliers_winedataset$pH %in% outliers9), ]
    }
    if (length(outliers10) > 0) {
        nill_outliers_winedataset <- nill_outliers_winedataset[-which(nill_outliers_winedataset$sulphates %in% outliers10), ]
    }

    outliers1 <- boxplot(nill_outliers_winedataset$fixed_acidity, plot = FALSE)$out
    outliers2 <- boxplot(nill_outliers_winedataset$volatile_acidity, plot = FALSE)$out
    outliers3 <- boxplot(nill_outliers_winedataset$citric_acid, plot = FALSE)$out
    outliers4 <- boxplot(nill_outliers_winedataset$residual_sugar, plot = FALSE)$out
    outliers5 <- boxplot(nill_outliers_winedataset$chlorides, plot = FALSE)$out
    outliers6 <- boxplot(nill_outliers_winedataset$free_sulfur_dioxide, plot = FALSE)$out
    outliers7 <- boxplot(nill_outliers_winedataset$total_sulfur_dioxide, plot = FALSE)$out
    outliers8 <- boxplot(nill_outliers_winedataset$density, plot = FALSE)$out
    outliers9 <- boxplot(nill_outliers_winedataset$pH, plot = FALSE)$out
    outliers10 <- boxplot(nill_outliers_winedataset$sulphates, plot = FALSE)$out
    outliers11 <- boxplot(nill_outliers_winedataset$alcohol, plot = FALSE)$out
}
```
```{r}
# Visualize all classes
boxplot(nill_outliers_winedataset)$out
```
```{r}
#seperate input variables and output variable
output_column = nill_outliers_winedataset$quality  
new_input_winedataset = nill_outliers_winedataset[,!(names(nill_outliers_winedataset) %in% c("quality"))]
```

```{r}
# Visualize indivizual classes
oldpar1 = par(mfrow = c(2,6))
for ( i in 1:11 ) {
  boxplot(new_input_winedataset[[i]])
  mtext(names(new_input_winedataset)[i], cex = 1, side = 1, line = 2)
}
par(oldpar1) 
```

```{r}
#standarize new dataset with the help of scale func in R
scale_inputs <- scale(new_input_winedataset)
scale_inputs
```
```{r}
#standarize outputs with the help of scale func in R
scale_outputs <- scale(output_column)
scale_outputs
```

```{r}
# NbClust giving best number of clusters
set.seed(26)
clusterNo=NbClust(scale_inputs,distance="euclidean", min.nc=2,max.nc=10,method="kmeans",index="all")
```
```{r}
# Elbow method
fviz_nbclust(scale_inputs, kmeans, method = "wss") + geom_vline(xintercept = 4, linetype = 2)+ 
  labs(subtitle = "Elbow method")
```

```{r}
# Silhouette method
fviz_nbclust(scale_inputs, kmeans, method = "silhouette")+
  labs(subtitle = "Silhouette method")
```
```{r}
# Gap statistic
# nboot = 50 to keep the function speedy. 
# recommended value: nboot= 500 for your analysis.
# Use verbose = FALSE to hide computing progression.
set.seed(123)
fviz_nbclust(scale_inputs, kmeans, nstart = 25,  method = "gap_stat", nboot = 50)+
  labs(subtitle = "Gap statistic method")
```

```{r}
# kmean for k = 2
clustering_result2 <- kmeans(scale_inputs, 2)
fviz_cluster(clustering_result2, data = scale_inputs, geom="point", ellipse.type="convex", ggthme=theme_bw())
```
```{r}
# kmean for k = 3
clustering_result3 <- kmeans(scale_inputs, 3)
fviz_cluster(clustering_result3, data = scale_inputs, geom="point", ellipse.type="convex", ggthme=theme_bw())
```

```{r}
# kmean for k = 4
clustering_result4 <- kmeans(scale_inputs, 4)
fviz_cluster(clustering_result4, data = scale_inputs, geom="point", ellipse.type="convex", ggthme=theme_bw())
```

```{r}
#get more information(wss) about clusters for k=2
clustering_result2
```
```{r}
clustering_result2$betweenss/clustering_result2$totss
```

```{r}
#get more information(wss) about clusters for k=3
clustering_result3
```
```{r}
clustering_result3$betweenss/clustering_result3$totss
```

```{r}
#get more information(wss) about clusters for k=4
clustering_result4
```
```{r}
clustering_result4$betweenss/clustering_result4$totss
```

```{r}
#CM for k=2
table(output_column,clustering_result2$cluster)  
```
```{r}
#CM for k=3
table(output_column,clustering_result3$cluster) 
```
```{r}
#CM for k=4
table(output_column,clustering_result4$cluster) 
```
```{r}
subsample <- list()
for(i in 1:2){
  subsample[[i]]<- nill_outliers_winedataset[clustering_result2$cluster==i,]
}
```
```{r}
table(subsample[[1]]$quality)
```
```{r}
table(subsample[[2]]$quality)
```
```{r}
#Accuracy considering cluster 1 (k=2)
TP2_1 = 610
FN2_1 = 415
FP2_1 = 724 + 145 + 21
TN2_1 = 1079 + 626 + 113
accuracy2_1 = (TP2_1 + TN2_1)/ (TP2_1 + FP2_1 + FN2_1 + TN2_1)
accuracy2_1
```
```{r}
#Accuracy considering cluster 2 (k=2)
TP2_2 = 1079 + 626 + 113
FN2_2 = 724 + 145 + 21
FP2_2 = 415
TN2_2 = 610
accuracy2_2 = (TP2_2 + TN2_2)/ (TP2_2 + FP2_2 + FN2_2 + TN2_2)
accuracy2_2
```
```{r}
#classification accuracy
ova_acc = (610 + (1079 + 626 + 113)) / (610 + 415 + (724 + 145 + 21) + (1079 + 626 + 113))
ova_acc
```
```{r}
#recall when k = 2
recall2 = TP2_1 / (TP2_1 + FN2_1)
recall2
```
```{r}
#precision when k = 2
precision2 = TP2_1 / (TP2_1 + FP2_1)
precision2
```

```{r}
#k = 3
subsample3 <- list()
for(i in 1:3){
  subsample3[[i]]<- nill_outliers_winedataset[clustering_result3$cluster==i,]
}
```
```{r}
table(subsample3[[1]]$quality)
```
```{r}
table(subsample3[[2]]$quality)
```
```{r}
table(subsample3[[3]]$quality)
```
```{r}
#Accuracy considering cluster 1 (k=3)
TP3_1 = 571
FN3_1 = 138 + 316
FP3_1 = 638 + 130 + 18
TN3_1 = 551 + 399 + 68 + 614 + 242
accuracy3 = (TP3_1 + TN3_1)/ (TP3_1 + FP3_1 + FN3_1 + TN3_1)
accuracy3
```
```{r}
#recall when k = 3
recall3 = TP3_1 / (TP3_1 + FN3_1)
recall3
```
```{r}
#precision when k = 3
precision3 = TP3_1 / (TP3_1 + FP3_1)
precision3
```


```{r}
#k = 4
subsample4 <- list()
for(i in 1:4){
  subsample4[[i]]<- nill_outliers_winedataset[clustering_result4$cluster==i,]
}
```
```{r}
table(subsample4[[1]]$quality)
```
```{r}
table(subsample4[[2]]$quality)
```
```{r}
table(subsample4[[3]]$quality)
```
```{r}
table(subsample4[[4]]$quality)
```
```{r}
#Accuracy considering cluster 1 (k=4)
TP4_1 = 528
FN4_1 = 56 + 234 + 207
FP4_1 = 542 + 114 + 16
TN4_1 = 414 + 157 + 30 + 507 + 176 + 33 + 340 + 324 + 55
accuracy4 = (TP4_1 + TN4_1)/ (TP4_1 + FP4_1 + FN4_1 + TN4_1)
accuracy4
```
```{r}
#recall when k = 4
recall4 = TP4_1 / (TP4_1 + FN4_1)
recall4
```
```{r}
#precision when k = 4
precision4 = TP4_1 / (TP4_1 + FP4_1)
precision4
```
According the the recall values, k = 2 clustering option gives us the most probability to retrieve the relevant items. So, winner should be **k = 2**

```{r}
#compute PCA
winedata_PCA  <- prcomp(nill_outliers_winedataset, scale = TRUE)
summary(winedata_PCA)
```
```{r}
fviz_eig(winedata_PCA)
```
```{r}
fviz_pca_ind(winedata_PCA,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```
```{r}
fviz_pca_var(winedata_PCA,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```
```{r}
head(winedata_PCA[5])
```
```{r}
new_pca_dataset = winedata_PCA[[5]]
new_pca <- list()
for(i in 1:12){
  new_pca[[i]]<- new_pca_dataset[[i]]
}

new_pca_dataset = new_pca_dataset[ -c(1:9) ]
summary(new_pca_dataset)
```

```{r}
#standard deviation of PCA
std_dev_pca <- winedata_PCA$sdev
std_dev_pca
```

```{r}
#compute variance
pca_var <- std_dev_pca^2
```

```{r}
pca_var[1:12]
```

```{r}
#proportion of variance explained
prop_varex_pca <- pca_var/sum(pca_var)
```

```{r}
prop_varex_pca[1:12]
```
```{r}
#cumulative scree plot
plot(cumsum(prop_varex_pca), xlab = "Principal Component",
              ylab = "Cumulative Proportion of Variance Explained",
              type = "b")
```

Above plot shows that 9 components results in variance close to ~ 96%. Therefore, in this case, we’ll select number of components as 9 [PC1 to PC9] and proceed as **new transformed dataset**.

```{r}
#add a input set with principal components
input_set.data <- data.frame(winedata_PCA$x)
```

```{r}
input_set.data <- input_set.data[,1:9]
```

```{r}
# kmean for k = 2 pca
pca_clustering_result3 <- kmeans(input_set.data, 3)
pca_clustering_result3
```

## Objective 02

```{r}
# install package
install.packages("neuralnet")
install.packages("forecast")
install.packages("pracma")
install.packages("tidymodels")
install.packages("summarytools")
install.packages("Metrics")
install.packages("MLmetrics")
```

```{r}
# load library
library(neuralnet)
library(forecast)
library(pracma)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(zoo)
library(tidymodels)
library(knitr)
library(dplyr)
library(summarytools)
library(Metrics)
library(MLmetrics)
```

```{r}
# import Excel file into R
uow_dataset <- read_excel("S:\\UoW\\YR3\\ML\\cw\\UoW_load.xlsx")
```

```{r}
# get column name
names(uow_dataset) <- gsub(" ", "_", names(uow_dataset))
colnames(uow_dataset)
```
```{r}
#make this example reproducible
set.seed(1)
```

```{r}
#rename the dataset columns
names(uow_dataset)[names(uow_dataset) == "09:00"] <- "NineHr"
names(uow_dataset)[names(uow_dataset) == "10:00"] <- "TenHr"
names(uow_dataset)[names(uow_dataset) == "11:00"] <- "ElevenHr"
```

```{r}
head(uow_dataset)
```

```{r}
#use first 430 sample of dataset as training set and rest as test set

train_df  <- uow_dataset[1:430, ]
test_df   <- uow_dataset[431:500, ]
```

```{r}
frequency(train_df)
```
```{r}
#globally setting the theme for plots
theme_set(theme_bw())
par(mar = c(1,1,1,1))
```

```{r}
#training dataset as time-series dataset; 11:00 hour as the variable coulmn
ts_df = ts(train_df[]$ElevenHr, frequency = 1)
plot(ts_df) 
```

```{r}
#testing dataset as time-series dataset; 11:00 hour as the variable coulmn
tst_ts_df = ts(test_df[]$ElevenHr, frequency = 1)
plot(tst_ts_df) 
```


```{r}
#set input variables and output variables set with (t-1)
inputvar1_1 <- c()
outputvar1 <- c()

for(i in 1:429){
  input1_ =  ts_df[i]
  output_ =  ts_df[i+1]
  
  inputvar1_1 <- append(inputvar1_1, input1_)
  outputvar1 <- append(outputvar1, output_)
}
io_matrix1 <- data.frame(input1=inputvar1_1, output=outputvar1)
```


```{r}
#set input variables and output variables set with (t-2)
inputvar2_1 <- c()
inputvar2_2 <- c()
outputvar2 <- c()

for(i in 1:428){
  input1_ =  ts_df[i]
  input2_ =  ts_df[i+1]
  output_ =  ts_df[i+2]
  
  inputvar2_1 <- append(inputvar2_1, input1_)
  inputvar2_2 <- append(inputvar2_2, input2_)
  outputvar2 <- append(outputvar2, output_)
}
io_matrix2 <- data.frame(input1=inputvar2_1, input2=inputvar2_2, output=outputvar2)
```


```{r}
#set input variables and output variables set with (t-3)
inputvar3_1 <- c()
inputvar3_2 <- c()
inputvar3_3 <- c()
outputvar3 <- c()

for(i in 1:427){
  input1_ =  ts_df[i]
  input2_ =  ts_df[i+1]
  input3_ =  ts_df[i+2]
  output_ =  ts_df[i+3]
  
  inputvar3_1 <- append(inputvar3_1, input1_)
  inputvar3_2 <- append(inputvar3_2, input2_)
  inputvar3_3 <- append(inputvar3_3, input3_)
  outputvar3 <- append(outputvar3, output_)
}
io_matrix3 <- data.frame(input1=inputvar3_1, input2=inputvar3_2, input3=inputvar3_3, output=outputvar3)
```



```{r}
#set input variables and output variables set with (t-4)
inputvar4_1 <- c()
inputvar4_2 <- c()
inputvar4_3 <- c()
inputvar4_4 <- c()
outputvar4 <- c()

for(i in 1:426){
  input1_ =  ts_df[i]
  input2_ =  ts_df[i+1]
  input3_ =  ts_df[i+2]
  input4_ =  ts_df[i+3]
  output_ =  ts_df[i+4]
  
  inputvar4_1 <- append(inputvar4_1, input1_)
  inputvar4_2 <- append(inputvar4_2, input2_)
  inputvar4_3 <- append(inputvar4_3, input3_)
  inputvar4_4 <- append(inputvar4_4, input4_)
  outputvar4 <- append(outputvar4, output_)
}
io_matrix4 <- data.frame(input1=inputvar4_1, input2=inputvar4_2, input3=inputvar4_3, input4=inputvar4_4, output=outputvar4)
```


```{r}
#set input variables and output variables set with (t-7)
inputvar7_1 <- c()
inputvar7_2 <- c()
inputvar7_3 <- c()
inputvar7_4 <- c()
inputvar7_5 <- c()
inputvar7_6 <- c()
inputvar7_7 <- c()
outputvar7 <- c()

for(i in 1:423){
  input1_ =  ts_df[i]
  input2_ =  ts_df[i+1]
  input3_ =  ts_df[i+2]
  input4_ =  ts_df[i+3]
  input5_ =  ts_df[i+4]
  input6_ =  ts_df[i+5]
  input7_ =  ts_df[i+6]
  output_ =  ts_df[i+7]
  
  inputvar7_1 <- append(inputvar7_1, input1_)
  inputvar7_2 <- append(inputvar7_2, input2_)
  inputvar7_3 <- append(inputvar7_3, input3_)
  inputvar7_4 <- append(inputvar7_4, input4_)
  inputvar7_5 <- append(inputvar7_5, input5_)
  inputvar7_6 <- append(inputvar7_6, input6_)
  inputvar7_7 <- append(inputvar7_7, input7_)
  outputvar7 <- append(outputvar7, output_)
}
io_matrix7 <- data.frame(input1=inputvar7_1, input2=inputvar7_2, input3=inputvar7_3, input4=inputvar7_4, input5=inputvar7_5, input6=inputvar7_6, input7=inputvar7_7,output=outputvar7)
```

############################################### 
 
```{r}
#set input variables and output variables set with (t-1) Test dataset
inputvar1_1 <- c()
outputvar1 <- c()

for(i in 1:69){
  input1_ =  tst_ts_df[i]
  output_ =  tst_ts_df[i+1]
  
  inputvar1_1 <- append(inputvar1_1, input1_)
  outputvar1 <- append(outputvar1, output_)
}
io_matrix1_tst <- data.frame(input1=inputvar1_1, output=outputvar1)
```


```{r}
#set input variables and output variables set with (t-2)  Test dataset
inputvar2_1 <- c()
inputvar2_2 <- c()
outputvar2 <- c()

for(i in 1:68){
  input1_ =  tst_ts_df[i]
  input2_ =  tst_ts_df[i+1]
  output_ =  tst_ts_df[i+2]
  
  inputvar2_1 <- append(inputvar2_1, input1_)
  inputvar2_2 <- append(inputvar2_2, input2_)
  outputvar2 <- append(outputvar2, output_)
}
io_matrix2_tst <- data.frame(input1=inputvar2_1, input2=inputvar2_2, output=outputvar2)
```


```{r}
#set input variables and output variables set with (t-3)  Test dataset
inputvar3_1 <- c()
inputvar3_2 <- c()
inputvar3_3 <- c()
outputvar3 <- c()

for(i in 1:67){
  input1_ =  tst_ts_df[i]
  input2_ =  tst_ts_df[i+1]
  input3_ =  tst_ts_df[i+2]
  output_ =  tst_ts_df[i+3]
  
  inputvar3_1 <- append(inputvar3_1, input1_)
  inputvar3_2 <- append(inputvar3_2, input2_)
  inputvar3_3 <- append(inputvar3_3, input3_)
  outputvar3 <- append(outputvar3, output_)
}
io_matrix3_tst <- data.frame(input1=inputvar3_1, input2=inputvar3_2, input3=inputvar3_3, output=outputvar3)
```



```{r}
#set input variables and output variables set with (t-4)  Test dataset
inputvar4_1 <- c()
inputvar4_2 <- c()
inputvar4_3 <- c()
inputvar4_4 <- c()
outputvar4 <- c()

for(i in 1:66){
  input1_ =  tst_ts_df[i]
  input2_ =  tst_ts_df[i+1]
  input3_ =  tst_ts_df[i+2]
  input4_ =  tst_ts_df[i+3]
  output_ =  tst_ts_df[i+4]
  
  inputvar4_1 <- append(inputvar4_1, input1_)
  inputvar4_2 <- append(inputvar4_2, input2_)
  inputvar4_3 <- append(inputvar4_3, input3_)
  inputvar4_4 <- append(inputvar4_4, input4_)
  outputvar4 <- append(outputvar4, output_)
}
io_matrix4_tst <- data.frame(input1=inputvar4_1, input2=inputvar4_2, input3=inputvar4_3, input4=inputvar4_4, output=outputvar4)
```


```{r}
#set input variables and output variables set with (t-7)  Test dataset
inputvar7_1 <- c()
inputvar7_2 <- c()
inputvar7_3 <- c()
inputvar7_4 <- c()
inputvar7_5 <- c()
inputvar7_6 <- c()
inputvar7_7 <- c()
outputvar7 <- c()

for(i in 1:63){
  input1_ =  tst_ts_df[i]
  input2_ =  tst_ts_df[i+1]
  input3_ =  tst_ts_df[i+2]
  input4_ =  tst_ts_df[i+3]
  input5_ =  tst_ts_df[i+4]
  input6_ =  tst_ts_df[i+5]
  input7_ =  tst_ts_df[i+6]
  output_ =  tst_ts_df[i+7]
  
  inputvar7_1 <- append(inputvar7_1, input1_)
  inputvar7_2 <- append(inputvar7_2, input2_)
  inputvar7_3 <- append(inputvar7_3, input3_)
  inputvar7_4 <- append(inputvar7_4, input4_)
  inputvar7_5 <- append(inputvar7_5, input5_)
  inputvar7_6 <- append(inputvar7_6, input6_)
  inputvar7_7 <- append(inputvar7_7, input7_)
  outputvar7 <- append(outputvar7, output_)
}
io_matrix7_tst <- data.frame(input1=inputvar7_1, input2=inputvar7_2, input3=inputvar7_3, input4=inputvar7_4, input5=inputvar7_5, input6=inputvar7_6, input7=inputvar7_7,output=outputvar7)
```

```{r}
#Input/Output matrix for T-1 train
io_matrix1
```
```{r}
#Input/Output matrix for T-2 train
io_matrix2
```
```{r}
#Input/Output matrix for T-3 train
io_matrix3
```
```{r}
#Input/Output matrix for T-4 train
io_matrix4
```
```{r}
#Input/Output matrix for T-7 train
io_matrix7
```

```{r}
#Input/Output matrix for T-1 test
io_matrix1_tst
```
```{r}
#Input/Output matrix for T-2 test
io_matrix2_tst
```
```{r}
#Input/Output matrix for T-3 test
io_matrix3_tst
```
```{r}
#Input/Output matrix for T-4 test
io_matrix4_tst
```
```{r}
#Input/Output matrix for T-7 test
io_matrix7_tst
```

```{r}
#define Min-Max normalization function
min_max_norm <- function(x) {
    (x - min(x)) / (max(x) - min(x))
  }
```

```{r}
#apply Min-Max normalization to train IO matrices
io_matrix1_norm <- as.data.frame(lapply(io_matrix1, min_max_norm))
io_matrix2_norm <- as.data.frame(lapply(io_matrix2, min_max_norm))
io_matrix3_norm <- as.data.frame(lapply(io_matrix3, min_max_norm))
io_matrix4_norm <- as.data.frame(lapply(io_matrix4, min_max_norm))
io_matrix7_norm <- as.data.frame(lapply(io_matrix7, min_max_norm))
```

```{r}
#apply Min-Max normalization to test IO matrices
io_matrix1_tst_norm <- as.data.frame(lapply(io_matrix1_tst, min_max_norm))
io_matrix2_tst_norm <- as.data.frame(lapply(io_matrix2_tst, min_max_norm))
io_matrix3_tst_norm <- as.data.frame(lapply(io_matrix3_tst, min_max_norm))
io_matrix4_tst_norm <- as.data.frame(lapply(io_matrix4_tst, min_max_norm))
io_matrix7_tst_norm <- as.data.frame(lapply(io_matrix7_tst, min_max_norm))
```

```{r}
#AR analysic for training dataset when T-1
AR_1 = arima(train_df$ElevenHr, order = c(1,0,0))
print(AR_1)
```
```{r}
#AR analysic for training dataset when T-2
AR_2 = arima(train_df$ElevenHr, order = c(2,0,0))
print(AR_2)
```

```{r}
#AR analysic for training dataset when T-3
AR_3 = arima(train_df$ElevenHr, order = c(3,0,0))
print(AR_3)
```

```{r}
#AR analysic for training dataset when T-4
AR_4 = arima(train_df$ElevenHr, order = c(4,0,0))
print(AR_4)
```

```{r}
#AR analysic for training dataset when T-7
AR_7 = arima(train_df$ElevenHr, order = c(7,0,0))
print(AR_7)
```

```{r}
#Neural Network training data = io_matrix1_norm
io_matrix1_nn <- neuralnet(io_matrix1_norm$output ~ input1, data=io_matrix1_norm, hidden=c(2,1), linear.output=FALSE, threshold=0.01)
io_matrix1_nn$result.matrix
plot(io_matrix1_nn)
```

```{r}
#Neural Network training data = io_matrix2_norm
io_matrix2_nn <- neuralnet(io_matrix2_norm$output ~ input1+input2, data=io_matrix2_norm, hidden=c(2,1), linear.output=FALSE, threshold=0.01)
io_matrix2_nn$result.matrix
plot(io_matrix2_nn)
```
```{r}
#Neural Network training data = io_matrix3_norm
io_matrix3_nn <- neuralnet(io_matrix3_norm$output ~ input1+input2+input3, data=io_matrix3_norm, hidden=c(2,1), linear.output=FALSE, threshold=0.01)
io_matrix3_nn$result.matrix
plot(io_matrix3_nn)
```

```{r}
#Neural Network training data = io_matrix4_norm
io_matrix4_nn <- neuralnet(io_matrix4_norm$output ~ input1+input2+input3+input4, data=io_matrix4_norm, hidden=c(2,1), linear.output=FALSE, threshold=0.01)
io_matrix4_nn$result.matrix
plot(io_matrix4_nn)
```

```{r}
#Neural Network training data = io_matrix7_norm
io_matrix7_nn <- neuralnet(io_matrix7_norm$output ~ input1+input2+input3+input4+input5+input6+input7, data=io_matrix7_norm, hidden=c(2,1), linear.output=FALSE, threshold=0.01)
io_matrix7_nn$result.matrix
plot(io_matrix7_nn)
```

```{r}
## Prediction using neural network (t-1)
Predict_mat1=compute(io_matrix1_nn, io_matrix1_tst_norm)

# Converting probabilities into binary classes setting threshold level 0.5
prob_mat1 <- Predict_mat1$net.result
pred_mat1 <- ifelse(prob_mat1>0.5, 1, 0)
pred_mat1
```
```{r}
## Prediction using neural network - (t-2)
Predict_mat2=compute(io_matrix2_nn, io_matrix2_tst_norm)

# Converting probabilities into binary classes setting threshold level 0.5
prob_mat2 <- Predict_mat2$net.result
pred_mat2 <- ifelse(prob_mat2>0.5, 1, 0)
pred_mat2
```
```{r}
## Prediction using neural network - (t-3)
Predict_mat3=compute(io_matrix3_nn, io_matrix3_tst_norm)

# Converting probabilities into binary classes setting threshold level 0.5
prob_mat3 <- Predict_mat3$net.result
pred_mat3 <- ifelse(prob_mat3>0.5, 1, 0)
pred_mat3
```

```{r}
## Prediction using neural network - (t-4)
Predict_mat4=compute(io_matrix4_nn, io_matrix4_tst_norm)

# Converting probabilities into binary classes setting threshold level 0.5
prob_mat4 <- Predict_mat4$net.result
pred_mat4 <- ifelse(prob_mat4>0.5, 1, 0)
pred_mat4
```

```{r}
## Prediction using neural network - (t-7)
Predict_mat7=compute(io_matrix7_nn, io_matrix7_tst_norm)

# Converting probabilities into binary classes setting threshold level 0.5
prob_mat7 <- Predict_mat7$net.result
pred_mat7 <- ifelse(prob_mat7>0.5, 1, 0)
pred_mat7
```

**MAE**

```{r}
#MAE value t-1
mae(io_matrix1_tst_norm$output, pred_mat1)
```
```{r}
#MAE value t-2
mae(io_matrix2_tst_norm$output, pred_mat2)
```
```{r}
#MAE value t-3
mae(io_matrix3_tst_norm$output, pred_mat3)
```
```{r}
#MAE value t-4
mae(io_matrix4_tst_norm$output, pred_mat4)
```
```{r}
#MAE value t-7
mae(io_matrix7_tst_norm$output, pred_mat7)
```
**RMSE**

```{r}
#MAE value t-1
rmse(io_matrix1_tst_norm$output, pred_mat1)
```
```{r}
#MAE value t-2
rmse(io_matrix2_tst_norm$output, pred_mat2)
```
```{r}
#MAE value t-3
rmse(io_matrix3_tst_norm$output, pred_mat3)
```
```{r}
#MAE value t-4
rmse(io_matrix4_tst_norm$output, pred_mat4)
```
```{r}
#MAE value t-7
rmse(io_matrix7_tst_norm$output, pred_mat7)
```



```{r}
stby(
  data = io_matrix1_norm,
  INDICES = io_matrix1_norm$output, # by Output
  FUN = descr, # descriptive statistics
  stats = "common" # most common descr. stats
)
```

```{r}
stby(
  data = io_matrix2_norm,
  INDICES = io_matrix2_norm$output, # by Output
  FUN = descr, # descriptive statistics
  stats = "common" # most common descr. stats
)
```
```{r}
stby(
  data = io_matrix3_norm,
  INDICES = io_matrix3_norm$output, # by Output
  FUN = descr, # descriptive statistics
  stats = "common" # most common descr. stats
)
```

```{r}
stby(
  data = io_matrix4_norm,
  INDICES = io_matrix4_norm$output, # by Output
  FUN = descr, # descriptive statistics
  stats = "common" # most common descr. stats
)
```

```{r}
stby(
  data = io_matrix7_norm,
  INDICES = io_matrix7_norm$output, # by Output
  FUN = descr, # descriptive statistics
  stats = "common" # most common descr. stats
)
```







